-- Create a table for public profiles (users)
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.users enable row level security;

-- Create policies
create policy "Public profiles are viewable by everyone." on public.users
  for select using (true);

create policy "Users can insert their own profile." on public.users
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.users
  for update using (auth.uid() = id);

-- Trigger to handle new user signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.users (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid duplication error on re-run
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Backfill existing users
insert into public.users (id, email)
select id, email from auth.users
on conflict (id) do nothing;

-- Ascensions Table
create table if not exists public.ascensions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  coins integer default 0,
  diamonds integer default 0,
  exp integer default 0,
  is_completed boolean default false,
  user_id uuid references public.users(id) not null
);

alter table public.ascensions enable row level security;

create policy "Users can view their own ascensions." on public.ascensions
  for select using (auth.uid() = user_id);

create policy "Users can insert their own ascensions." on public.ascensions
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own ascensions." on public.ascensions
  for update using (auth.uid() = user_id);

create policy "Users can delete their own ascensions." on public.ascensions
  for delete using (auth.uid() = user_id);

-- Journal Entries Table
create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  user_id uuid references public.users(id) not null
);

alter table public.journal_entries enable row level security;

create policy "Users can view their own journal entries." on public.journal_entries
  for select using (auth.uid() = user_id);

create policy "Users can insert their own journal entries." on public.journal_entries
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own journal entries." on public.journal_entries
  for update using (auth.uid() = user_id);

create policy "Users can delete their own journal entries." on public.journal_entries
  for delete using (auth.uid() = user_id);

-- User Stats Table
create table if not exists public.user_stats (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.users(id) not null unique,
  coins integer default 100,
  diamonds integer default 20,
  exp integer default 0,
  level integer default 1
);

alter table public.user_stats enable row level security;

create policy "Users can view their own stats." on public.user_stats
  for select using (auth.uid() = user_id);

create policy "Users can insert their own stats." on public.user_stats
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own stats." on public.user_stats
  for update using (auth.uid() = user_id);

-- Daily Activity Table
create table if not exists public.daily_activity (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.users(id) not null,
  activity_date date not null,
  completed_tasks jsonb default '[]'::jsonb
);

alter table public.daily_activity enable row level security;

create policy "Users can view their own daily activity." on public.daily_activity
  for select using (auth.uid() = user_id);

create policy "Users can insert their own daily activity." on public.daily_activity
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own daily activity." on public.daily_activity
  for update using (auth.uid() = user_id);

create policy "Users can delete their own daily activity." on public.daily_activity
  for delete using (auth.uid() = user_id);
