-- Create a table for Journal Entries
create table journal_entries (
  id bigint generated by default as identity primary key,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
